/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Analog/Digital mode.: Analog mode. */
#define PIO010_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO010_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO010_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO011_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO011_FUNC_ALT6 0x06u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO012_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 6. */
#define PIO012_FUNC_ALT6 0x06u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO013_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO013_FUNC_ALT7 0x07u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO014_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO014_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Analog mode. */
#define PIO015_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO015_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO015_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO016_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO016_FUNC_ALT2 0x02u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO018_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO018_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO019_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO019_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO020_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO020_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO021_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO021_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO022_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO022_FUNC_ALT7 0x07u
/*!
 * @brief Select Analog/Digital mode.: Analog mode. */
#define PIO023_DIGIMODE_ANALOG 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO023_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO023_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO024_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO024_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO025_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO025_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO026_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO026_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO027_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO027_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO028_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO028_FUNC_ALT5 0x05u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO029_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO029_FUNC_ALT5 0x05u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO02_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO02_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO030_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO030_FUNC_ALT5 0x05u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO031_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO031_FUNC_ALT5 0x05u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO03_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO03_FUNC_ALT3 0x03u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO05_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO05_FUNC_ALT7 0x07u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO07_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO07_FUNC_ALT7 0x07u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO08_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 4. */
#define PIO08_FUNC_ALT4 0x04u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO09_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO09_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO10_FUNC_ALT5 0x05u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO110_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO110_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO111_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO111_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO113_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO113_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO114_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO114_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO116_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO116_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO118_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO118_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO119_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO119_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO11_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO120_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO120_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO121_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO121_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO122_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO122_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO123_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO123_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO124_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO124_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO125_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO125_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO126_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO126_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO127_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO127_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO128_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO128_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO12_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO12_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO131_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO131_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO13_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 4. */
#define PIO14_FUNC_ALT4 0x04u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 4. */
#define PIO15_FUNC_ALT4 0x04u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO16_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO17_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO18_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO19_FUNC_ALT1 0x01u

/*! @name PIO1_7 (number 18), RELAY
  @{ */
#define BOARD_INITPINS_RELAY_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_RELAY_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_RELAY_PIN 7U    /*!<@brief 1U pin index: 7 */
                                       /* @} */

/*! @name PIO1_25 (number 59), CAN_PHY_EN
  @{ */
#define BOARD_INITPINS_CAN_PHY_EN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CAN_PHY_EN_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_CAN_PHY_EN_PIN 25U   /*!<@brief 1U pin index: 25 */
                                            /* @} */

/*! @name PIO1_6 (number 15), PHY_INT
  @{ */
#define BOARD_INITPINS_PHY_INT_PORT 1U /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_PHY_INT_PIN 6U  /*!<@brief 1U pin index: 6 */
                                       /* @} */

/*! @name PIO1_31 (number 92), LED9
  @{ */
#define BOARD_INITPINS_LED9_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED9_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_LED9_PIN 31U   /*!<@brief 1U pin index: 31 */
                                      /* @} */

/*! @name PIO1_22 (number 43), LED7
  @{ */
#define BOARD_INITPINS_LED7_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED7_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_LED7_PIN 22U   /*!<@brief 1U pin index: 22 */
                                      /* @} */

/*! @name PIO0_21 (number 77), LED6
  @{ */
#define BOARD_INITPINS_LED6_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED6_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_LED6_PIN 21U   /*!<@brief 0U pin index: 21 */
                                      /* @} */

/*! @name PIO0_18 (number 72), PHY_WAKE_INOUT
  @{ */
#define BOARD_INITPINS_PHY_WAKE_INOUT_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_PHY_WAKE_INOUT_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_PHY_WAKE_INOUT_PIN 18U   /*!<@brief 0U pin index: 18 */
                                                /* @} */

/*! @name PIO0_19 (number 91), PHY_EN
  @{ */
#define BOARD_INITPINS_PHY_EN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_PHY_EN_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_PHY_EN_PIN 19U   /*!<@brief 0U pin index: 19 */
                                        /* @} */

/*! @name PIO1_21 (number 37), LED8
  @{ */
#define BOARD_INITPINS_LED8_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED8_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_LED8_PIN 21U   /*!<@brief 1U pin index: 21 */
                                      /* @} */

/*! @name PIO1_19 (number 16), PHY_RESET
  @{ */
#define BOARD_INITPINS_PHY_RESET_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_PHY_RESET_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_PHY_RESET_PIN 19U   /*!<@brief 1U pin index: 19 */
                                           /* @} */

/*! @name CLKOUT (number 27), CLKOUT
  @{ */
/* @} */

/*! @name PIO0_14 (number 69), RX_ERROR
  @{ */
#define BOARD_INITPINS_RX_ERROR_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_RX_ERROR_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_RX_ERROR_PIN 14U   /*!<@brief 0U pin index: 14 */
                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M4F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
