/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_reset.h"
#include "fsl_usart.h"
#include "fsl_clock.h"
#include "fsl_gpio.h"
#include "fsl_adc.h"
#include "fsl_spi.h"
#include "fsl_i2c.h"
#include "fsl_sctimer.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define USART_1_PERIPHERAL ((USART_Type *)FLEXCOMM0)
/* Definition of the clock source frequency */
#define USART_1_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_Flexcomm0)
/* Alias for GPIO peripheral */
#define GPIO_1_GPIO GPIO
/* Alias for ADC0 peripheral */
#define ADC_1_PERIPHERAL ADC0
/* BOARD_InitPeripherals defines for FLEXCOMM1 */
/* Definition of peripheral ID */
#define SPI_1_PERIPHERAL ((SPI_Type *)FLEXCOMM1)
/* Definition of the clock source frequency */
#define SPI_1_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_Flexcomm1)
/* BOARD_InitPeripherals defines for FLEXCOMM2 */
/* Definition of peripheral ID */
#define SPI_2_PERIPHERAL ((SPI_Type *)FLEXCOMM2)
/* Definition of the clock source frequency */
#define SPI_2_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_Flexcomm2)
/* BOARD_InitPeripherals defines for FLEXCOMM4 */
/* Definition of peripheral ID */
#define SPI_3_PERIPHERAL ((SPI_Type *)FLEXCOMM4)
/* Definition of the clock source frequency */
#define SPI_3_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_Flexcomm4)
/* BOARD_InitPeripherals defines for FLEXCOMM7 */
/* Definition of peripheral ID */
#define I2C_1_PERIPHERAL ((I2C_Type *)FLEXCOMM7)
/* Definition of the clock source frequency */
#define I2C_1_CLOCK_SOURCE CLOCK_GetFreq(kCLOCK_Flexcomm7)
/* BOARD_InitPeripherals defines for SCT0 */
/* Definition of peripheral ID */
#define SCTIMER_1_PERIPHERAL SCT0
/* Definition of clock source frequency */
#define SCTIMER_1_CLOCK_FREQ CLOCK_GetFreq(kCLOCK_BusClk)
/* SCTimer_1 interrupt vector ID (number). */
#define SCTIMER_1_IRQN SCT0_IRQn
/* SCTimer_1 interrupt handler identifier. */
#define SCTIMER_1_IRQHANDLER SCT0_IRQHandler
/* SCTimer output 0 mask */
#define SCTIMER_OUTPUT_0_MASK (1U << kSCTIMER_Out_0)
/* SCTimer output 1 mask */
#define SCTIMER_OUTPUT_1_MASK (1U << kSCTIMER_Out_1)
/* SCTimer output 2 mask */
#define SCTIMER_OUTPUT_2_MASK (1U << kSCTIMER_Out_2)
/* SCTimer output 3 mask */
#define SCTIMER_OUTPUT_3_MASK (1U << kSCTIMER_Out_3)
/* SCTimer output 4 mask */
#define SCTIMER_OUTPUT_4_MASK (1U << kSCTIMER_Out_4)
/* SCTimer output 5 mask */
#define SCTIMER_OUTPUT_5_MASK (1U << kSCTIMER_Out_5)
/* SCTimer output 6 mask */
#define SCTIMER_OUTPUT_6_MASK (1U << kSCTIMER_Out_6)
/* SCTimer output 7 mask */
#define SCTIMER_OUTPUT_7_MASK (1U << kSCTIMER_Out_7)

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const usart_config_t USART_1_config;
extern const adc_config_t ADC_1configStruct;
extern const spi_master_config_t SPI_1_config;
extern const spi_master_config_t SPI_2_config;
extern const spi_master_config_t SPI_3_config;
extern const i2c_master_config_t I2C_1_config;
extern const sctimer_config_t SCTimer_1_initConfig;
extern const sctimer_pwm_signal_param_t SCTimer_1_pwmSignalsConfig[1];
extern uint32_t SCTimer_1_pwmEvent[1];

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
